.PHONY: default clean

default:
	@echo "---------- Telemarketing Phone Number List ----------"
	@make -sC phone_number_list run
	@echo
	@echo "---------- Sum of Digits in a String ----------"
	@make -sC sum_of_digits run

clean:
	@make -sC phone_number_list clean
	@make -sC sum_of_digits clean
