.PHONY: default clean

default:
	@echo "---------- RetailItem Demo ----------"
	@make -sC retail_item run
	@echo
	@echo "---------- Payroll Demo ----------"
	@make -sC payroll run

clean:
	@make -sC retail_item clean
	@make -sC payroll clean
