.PHONY: default clean

default:
	@echo "---------- Software Sales Demo ----------"
	@make -sC software_sales run
	@echo
	@echo "---------- BankCharges Demo ----------"
	@make -sC bank_charges run

clean:
	@make -sC software_sales clean
	@make -sC bank_charges clean
